// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: proto/acc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty response for AccService
type AEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AEmpty) Reset() {
	*x = AEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AEmpty) ProtoMessage() {}

func (x *AEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AEmpty.ProtoReflect.Descriptor instead.
func (*AEmpty) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{0}
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // account request token
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // account unique id
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{2}
}

func (x *UUID) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UIDS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []string `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *UIDS) Reset() {
	*x = UIDS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UIDS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIDS) ProtoMessage() {}

func (x *UIDS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIDS.ProtoReflect.Descriptor instead.
func (*UIDS) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{3}
}

func (x *UIDS) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type SKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids     []string `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
	Filterid bool     `protobuf:"varint,2,opt,name=filterid,proto3" json:"filterid,omitempty"`
	Keyword  string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *SKeys) Reset() {
	*x = SKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKeys) ProtoMessage() {}

func (x *SKeys) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKeys.ProtoReflect.Descriptor instead.
func (*SKeys) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{4}
}

func (x *SKeys) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *SKeys) GetFilterid() bool {
	if x != nil {
		return x.Filterid
	}
	return false
}

func (x *SKeys) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // account email
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{5}
}

func (x *Email) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Emails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Email `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Emails) Reset() {
	*x = Emails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emails) ProtoMessage() {}

func (x *Emails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emails.ProtoReflect.Descriptor instead.
func (*Emails) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{6}
}

func (x *Emails) GetItems() []*Email {
	if x != nil {
		return x.Items
	}
	return nil
}

type AccPwd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acc string `protobuf:"bytes,1,opt,name=acc,proto3" json:"acc,omitempty"` // account uuid, email or phone
	Pwd string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"` // account login password enripted by RSA + Base64
}

func (x *AccPwd) Reset() {
	*x = AccPwd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccPwd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccPwd) ProtoMessage() {}

func (x *AccPwd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccPwd.ProtoReflect.Descriptor instead.
func (*AccPwd) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{7}
}

func (x *AccPwd) GetAcc() string {
	if x != nil {
		return x.Acc
	}
	return ""
}

func (x *AccPwd) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type TagPwd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // request account uuid
	Tag  string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`   // target account uuid to change password
	Pwd  string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`   // target account login password enripted by RSA + Base64
}

func (x *TagPwd) Reset() {
	*x = TagPwd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagPwd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagPwd) ProtoMessage() {}

func (x *TagPwd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagPwd.ProtoReflect.Descriptor instead.
func (*TagPwd) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{8}
}

func (x *TagPwd) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TagPwd) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagPwd) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type IDEMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`   // uuid for the profile
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"` // store composer email address to update
}

func (x *IDEMail) Reset() {
	*x = IDEMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDEMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDEMail) ProtoMessage() {}

func (x *IDEMail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDEMail.ProtoReflect.Descriptor instead.
func (*IDEMail) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{9}
}

func (x *IDEMail) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *IDEMail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type IDEMails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*IDEMail `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *IDEMails) Reset() {
	*x = IDEMails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDEMails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDEMails) ProtoMessage() {}

func (x *IDEMails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDEMails.ProtoReflect.Descriptor instead.
func (*IDEMails) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{10}
}

func (x *IDEMails) GetItems() []*IDEMail {
	if x != nil {
		return x.Items
	}
	return nil
}

type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`       // account unique id
	Contact string `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"` // account nickname
	Email   string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`     // account email address
	Phone   string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`     // account email phone
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{11}
}

func (x *Contact) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Contact) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`          // account unique id
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`  // account nickname
	Heardurl string `protobuf:"bytes,3,opt,name=heardurl,proto3" json:"heardurl,omitempty"`  // account heardurl, the value set from wechat avatar or manual update by userself
	Sex      int64  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`           // account sex, 0:none, 1:male, 2:female, 3:neutral
	Birthday string `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty"`  // account birthday, the value set from real-name authentication
	Isverify bool   `protobuf:"varint,6,opt,name=isverify,proto3" json:"isverify,omitempty"` // status to indicate account if pass real-name autnenticated
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{12}
}

func (x *Profile) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Profile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Profile) GetHeardurl() string {
	if x != nil {
		return x.Heardurl
	}
	return ""
}

func (x *Profile) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *Profile) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *Profile) GetIsverify() bool {
	if x != nil {
		return x.Isverify
	}
	return false
}

type ProfAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`         // account unique id
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` // store name frist perfix string
	Province string `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"` // store name middle string
	City     string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`         // store name the last string
	Address  string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`   // store address string, it maybe empty
}

func (x *ProfAddr) Reset() {
	*x = ProfAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfAddr) ProtoMessage() {}

func (x *ProfAddr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfAddr.ProtoReflect.Descriptor instead.
func (*ProfAddr) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{13}
}

func (x *ProfAddr) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ProfAddr) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfAddr) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ProfAddr) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ProfAddr) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Avatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`         // account unique id
	Sex      int64  `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`          // account sex, 0:none, 1:male, 2:female, 3:neutral
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"` // account nickname
	Heardurl string `protobuf:"bytes,4,opt,name=heardurl,proto3" json:"heardurl,omitempty"` // account heardurl, the value set from wechat avatar
}

func (x *Avatar) Reset() {
	*x = Avatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Avatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Avatar) ProtoMessage() {}

func (x *Avatar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Avatar.ProtoReflect.Descriptor instead.
func (*Avatar) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{14}
}

func (x *Avatar) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Avatar) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *Avatar) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Avatar) GetHeardurl() string {
	if x != nil {
		return x.Heardurl
	}
	return ""
}

type Avatars struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profs []*Avatar `protobuf:"bytes,1,rep,name=profs,proto3" json:"profs,omitempty"`
}

func (x *Avatars) Reset() {
	*x = Avatars{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Avatars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Avatars) ProtoMessage() {}

func (x *Avatars) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Avatars.ProtoReflect.Descriptor instead.
func (*Avatars) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{15}
}

func (x *Avatars) GetProfs() []*Avatar {
	if x != nil {
		return x.Profs
	}
	return nil
}

type ProfStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`           // account unique id
	Unionid   string `protobuf:"bytes,2,opt,name=unionid,proto3" json:"unionid,omitempty"`     // wechat unionid bind with store account
	Logourl   string `protobuf:"bytes,3,opt,name=logourl,proto3" json:"logourl,omitempty"`     // store logo image url from heardurl field value of database
	Email     string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`         // store account email address, set when account generate
	Nickname  string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`   // store name frist perfix string
	Province  string `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`   // store name middle string
	City      string `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`           // store name the last string
	Address   string `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`     // store address string
	Signature string `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"` // store account auth signature
}

func (x *ProfStore) Reset() {
	*x = ProfStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfStore) ProtoMessage() {}

func (x *ProfStore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfStore.ProtoReflect.Descriptor instead.
func (*ProfStore) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{16}
}

func (x *ProfStore) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ProfStore) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

func (x *ProfStore) GetLogourl() string {
	if x != nil {
		return x.Logourl
	}
	return ""
}

func (x *ProfStore) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfStore) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfStore) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ProfStore) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ProfStore) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProfStore) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ProfStores struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profs []*ProfStore `protobuf:"bytes,1,rep,name=profs,proto3" json:"profs,omitempty"`
}

func (x *ProfStores) Reset() {
	*x = ProfStores{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfStores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfStores) ProtoMessage() {}

func (x *ProfStores) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfStores.ProtoReflect.Descriptor instead.
func (*ProfStores) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{17}
}

func (x *ProfStores) GetProfs() []*ProfStore {
	if x != nil {
		return x.Profs
	}
	return nil
}

type WxBind struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`       // account unique id
	Unionid string `protobuf:"bytes,2,opt,name=unionid,proto3" json:"unionid,omitempty"` // wechat unionid bind with store account
	Pwd     string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`         // account login password enripted by RSA + Base64
}

func (x *WxBind) Reset() {
	*x = WxBind{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxBind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxBind) ProtoMessage() {}

func (x *WxBind) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxBind.ProtoReflect.Descriptor instead.
func (*WxBind) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{18}
}

func (x *WxBind) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *WxBind) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

func (x *WxBind) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid   string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`     // verification request account id
	Router string `protobuf:"bytes,2,opt,name=router,proto3" json:"router,omitempty"` // verification request API router
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // verification request http method
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{19}
}

func (x *Role) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Role) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

func (x *Role) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pass bool `protobuf:"varint,1,opt,name=pass,proto3" json:"pass,omitempty"` // if account enable access router, ture is allow, false denied
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{20}
}

func (x *Result) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

type UserRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // traget role
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{21}
}

func (x *UserRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type TagRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // verification request account id
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // traget role
}

func (x *TagRole) Reset() {
	*x = TagRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagRole) ProtoMessage() {}

func (x *TagRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagRole.ProtoReflect.Descriptor instead.
func (*TagRole) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{22}
}

func (x *TagRole) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TagRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Machine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email  string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`   // store machine account email address, set when account generate
	Machsn string `protobuf:"bytes,2,opt,name=machsn,proto3" json:"machsn,omitempty"` // store name frist perfix string
}

func (x *Machine) Reset() {
	*x = Machine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{23}
}

func (x *Machine) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Machine) GetMachsn() string {
	if x != nil {
		return x.Machsn
	}
	return ""
}

type Composer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // store account email address, set when account generate
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` // store composer nickname
}

func (x *Composer) Reset() {
	*x = Composer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Composer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Composer) ProtoMessage() {}

func (x *Composer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Composer.ProtoReflect.Descriptor instead.
func (*Composer) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{24}
}

func (x *Composer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Composer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type CompSimp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`         // uuid for the profile
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`       // store composer email address to update
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"` // store composer nickname
}

func (x *CompSimp) Reset() {
	*x = CompSimp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompSimp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompSimp) ProtoMessage() {}

func (x *CompSimp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompSimp.ProtoReflect.Descriptor instead.
func (*CompSimp) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{25}
}

func (x *CompSimp) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CompSimp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CompSimp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RoleProf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`         // uuid for the profile
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`       // account email
	Phone    string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`       // account phone
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"` // account nickname
	Heardurl string `protobuf:"bytes,5,opt,name=heardurl,proto3" json:"heardurl,omitempty"` // account heardurl, the value set from wechat avatar
}

func (x *RoleProf) Reset() {
	*x = RoleProf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleProf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleProf) ProtoMessage() {}

func (x *RoleProf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleProf.ProtoReflect.Descriptor instead.
func (*RoleProf) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{26}
}

func (x *RoleProf) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RoleProf) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RoleProf) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RoleProf) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoleProf) GetHeardurl() string {
	if x != nil {
		return x.Heardurl
	}
	return ""
}

type RoleProfs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*RoleProf `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
}

func (x *RoleProfs) Reset() {
	*x = RoleProfs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleProfs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleProfs) ProtoMessage() {}

func (x *RoleProfs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleProfs.ProtoReflect.Descriptor instead.
func (*RoleProfs) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{27}
}

func (x *RoleProfs) GetProfiles() []*RoleProf {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type Search struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category int64  `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"` // category for search
	Keyword  string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`    // search keyword
	Role     string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`          // target role
}

func (x *Search) Reset() {
	*x = Search{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{28}
}

func (x *Search) GetCategory() int64 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *Search) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *Search) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SugMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email   string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`     // user input custom email address
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // feedback message content
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`       // user input contact name
	Phone   string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`     // user input phone number
	Links   string `protobuf:"bytes,5,opt,name=links,proto3" json:"links,omitempty"`     // uploaded image links
	Isbuy   int32  `protobuf:"varint,6,opt,name=isbuy,proto3" json:"isbuy,omitempty"`    // 0 for feedback, 1 for custom desing
}

func (x *SugMail) Reset() {
	*x = SugMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_acc_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SugMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SugMail) ProtoMessage() {}

func (x *SugMail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acc_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SugMail.ProtoReflect.Descriptor instead.
func (*SugMail) Descriptor() ([]byte, []int) {
	return file_proto_acc_proto_rawDescGZIP(), []int{29}
}

func (x *SugMail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SugMail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SugMail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SugMail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SugMail) GetLinks() string {
	if x != nil {
		return x.Links
	}
	return ""
}

func (x *SugMail) GetIsbuy() int32 {
	if x != nil {
		return x.Isbuy
	}
	return 0
}

var File_proto_acc_proto protoreflect.FileDescriptor

var file_proto_acc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x08, 0x0a, 0x06, 0x41, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x1d, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x1a, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x1a, 0x0a,
	0x04, 0x55, 0x49, 0x44, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0x51, 0x0a, 0x05, 0x53, 0x4b, 0x65,
	0x79, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x1d, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2c, 0x0a, 0x06, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2c, 0x0a, 0x06, 0x41, 0x63, 0x63,
	0x50, 0x77, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x63, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x40, 0x0a, 0x06, 0x54, 0x61, 0x67, 0x50, 0x77,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x33, 0x0a, 0x07, 0x49, 0x44, 0x45,
	0x4d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x30,
	0x0a, 0x08, 0x49, 0x44, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x44, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x63, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x73, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x22, 0x84, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x66,
	0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x66,
	0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65,
	0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65,
	0x61, 0x72, 0x64, 0x75, 0x72, 0x6c, 0x22, 0x2e, 0x0a, 0x07, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x73, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52,
	0x05, 0x70, 0x72, 0x6f, 0x66, 0x73, 0x22, 0xed, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x66, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x6f,
	0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x34, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x66, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x66, 0x73, 0x22, 0x48, 0x0a, 0x06,
	0x57, 0x78, 0x42, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e,
	0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x4a, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x22, 0x1c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73,
	0x22, 0x1e, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x22, 0x31, 0x0a, 0x07, 0x54, 0x61, 0x67, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x22, 0x37, 0x0a, 0x07, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x63, 0x68, 0x73, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x63, 0x68, 0x73, 0x6e, 0x22, 0x3c, 0x0a, 0x08,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x08, 0x43, 0x6f,
	0x6d, 0x70, 0x53, 0x69, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x82, 0x01, 0x0a,
	0x08, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x61, 0x72, 0x64, 0x75, 0x72,
	0x6c, 0x22, 0x38, 0x0a, 0x09, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x73, 0x12, 0x2b,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x66, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x06, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22,
	0x8f, 0x01, 0x0a, 0x07, 0x53, 0x75, 0x67, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x73, 0x62, 0x75, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x62, 0x75,
	0x79, 0x32, 0x9e, 0x0a, 0x0a, 0x03, 0x41, 0x63, 0x63, 0x12, 0x27, 0x0a, 0x08, 0x56, 0x69, 0x61,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x63, 0x50,
	0x77, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x56, 0x69, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x67,
	0x52, 0x6f, 0x6c, 0x65, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x6f, 0x6c, 0x65, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x63, 0x50,
	0x77, 0x64, 0x12, 0x27, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x63, 0x50, 0x77, 0x64, 0x1a, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x31, 0x0a, 0x0c, 0x52,
	0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x1a, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x73, 0x12, 0x2f,
	0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x1a, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x73, 0x12,
	0x2c, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x44, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x1a, 0x0d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2a, 0x0a,
	0x0c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x77, 0x64, 0x12, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x0c, 0x55, 0x6e, 0x62,
	0x69, 0x6e, 0x64, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x49, 0x44, 0x53, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x44, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x29, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44,
	0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x12, 0x29, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x12, 0x0b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x49, 0x44, 0x53, 0x1a, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x0d, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x12, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x4b, 0x65, 0x79, 0x73, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x55, 0x49, 0x44, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x29, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x64, 0x64, 0x4d,
	0x61, 0x63, 0x68, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x12, 0x2c,
	0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x12, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x1a,
	0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x12, 0x2d, 0x0a, 0x0b,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x55, 0x70, 0x43, 0x6f, 0x6d, 0x70, 0x12, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x53, 0x69, 0x6d, 0x70, 0x1a, 0x0d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2b, 0x0a, 0x0b, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x57, 0x78, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x57, 0x78, 0x42, 0x69, 0x6e, 0x64, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x57, 0x78, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x63, 0x63, 0x50, 0x77, 0x64, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x55,
	0x6e, 0x62, 0x69, 0x6e, 0x64, 0x57, 0x78, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x55, 0x49, 0x44, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x77, 0x64, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x67, 0x50,
	0x77, 0x64, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x2d, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x41, 0x64, 0x64,
	0x72, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x2d, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12,
	0x2f, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x49, 0x44, 0x53, 0x1a, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73,
	0x12, 0x2f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x73, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x2f, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d,
	0x61, 0x69, 0x6c, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x67, 0x4d,
	0x61, 0x69, 0x6c, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_acc_proto_rawDescOnce sync.Once
	file_proto_acc_proto_rawDescData = file_proto_acc_proto_rawDesc
)

func file_proto_acc_proto_rawDescGZIP() []byte {
	file_proto_acc_proto_rawDescOnce.Do(func() {
		file_proto_acc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_acc_proto_rawDescData)
	})
	return file_proto_acc_proto_rawDescData
}

var file_proto_acc_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_acc_proto_goTypes = []interface{}{
	(*AEmpty)(nil),     // 0: proto.AEmpty
	(*Token)(nil),      // 1: proto.Token
	(*UUID)(nil),       // 2: proto.UUID
	(*UIDS)(nil),       // 3: proto.UIDS
	(*SKeys)(nil),      // 4: proto.SKeys
	(*Email)(nil),      // 5: proto.Email
	(*Emails)(nil),     // 6: proto.Emails
	(*AccPwd)(nil),     // 7: proto.AccPwd
	(*TagPwd)(nil),     // 8: proto.TagPwd
	(*IDEMail)(nil),    // 9: proto.IDEMail
	(*IDEMails)(nil),   // 10: proto.IDEMails
	(*Contact)(nil),    // 11: proto.Contact
	(*Profile)(nil),    // 12: proto.Profile
	(*ProfAddr)(nil),   // 13: proto.ProfAddr
	(*Avatar)(nil),     // 14: proto.Avatar
	(*Avatars)(nil),    // 15: proto.Avatars
	(*ProfStore)(nil),  // 16: proto.ProfStore
	(*ProfStores)(nil), // 17: proto.ProfStores
	(*WxBind)(nil),     // 18: proto.WxBind
	(*Role)(nil),       // 19: proto.Role
	(*Result)(nil),     // 20: proto.Result
	(*UserRole)(nil),   // 21: proto.UserRole
	(*TagRole)(nil),    // 22: proto.TagRole
	(*Machine)(nil),    // 23: proto.Machine
	(*Composer)(nil),   // 24: proto.Composer
	(*CompSimp)(nil),   // 25: proto.CompSimp
	(*RoleProf)(nil),   // 26: proto.RoleProf
	(*RoleProfs)(nil),  // 27: proto.RoleProfs
	(*Search)(nil),     // 28: proto.Search
	(*SugMail)(nil),    // 29: proto.SugMail
}
var file_proto_acc_proto_depIdxs = []int32{
	5,  // 0: proto.Emails.items:type_name -> proto.Email
	9,  // 1: proto.IDEMails.items:type_name -> proto.IDEMail
	14, // 2: proto.Avatars.profs:type_name -> proto.Avatar
	16, // 3: proto.ProfStores.profs:type_name -> proto.ProfStore
	26, // 4: proto.RoleProfs.profiles:type_name -> proto.RoleProf
	1,  // 5: proto.Acc.ViaToken:input_type -> proto.Token
	19, // 6: proto.Acc.ViaRole:input_type -> proto.Role
	22, // 7: proto.Acc.AddRole:input_type -> proto.TagRole
	21, // 8: proto.Acc.AccRegister:input_type -> proto.UserRole
	7,  // 9: proto.Acc.AccLogin:input_type -> proto.AccPwd
	21, // 10: proto.Acc.RoleProfiles:input_type -> proto.UserRole
	28, // 11: proto.Acc.SearchInRole:input_type -> proto.Search
	9,  // 12: proto.Acc.UpdateEmail:input_type -> proto.IDEMail
	2,  // 13: proto.Acc.ResetSendPwd:input_type -> proto.UUID
	2,  // 14: proto.Acc.UnbindWechat:input_type -> proto.UUID
	2,  // 15: proto.Acc.GetToken:input_type -> proto.UUID
	3,  // 16: proto.Acc.GetAccEmails:input_type -> proto.UIDS
	2,  // 17: proto.Acc.GetProfile:input_type -> proto.UUID
	2,  // 18: proto.Acc.GetContact:input_type -> proto.UUID
	3,  // 19: proto.Acc.GetAvatars:input_type -> proto.UIDS
	4,  // 20: proto.Acc.SearchAvatars:input_type -> proto.SKeys
	2,  // 21: proto.Acc.DeleteAcc:input_type -> proto.UUID
	5,  // 22: proto.Acc.StoreAddMach:input_type -> proto.Email
	24, // 23: proto.Acc.StoreAddComp:input_type -> proto.Composer
	25, // 24: proto.Acc.StoreUpComp:input_type -> proto.CompSimp
	18, // 25: proto.Acc.StoreBindWx:input_type -> proto.WxBind
	7,  // 26: proto.Acc.StoreUnbindWx:input_type -> proto.AccPwd
	2,  // 27: proto.Acc.CompUnbindWx:input_type -> proto.UUID
	8,  // 28: proto.Acc.CompResetPwd:input_type -> proto.TagPwd
	13, // 29: proto.Acc.StoreRename:input_type -> proto.ProfAddr
	2,  // 30: proto.Acc.StoreProfile:input_type -> proto.UUID
	3,  // 31: proto.Acc.StoreProfiles:input_type -> proto.UIDS
	6,  // 32: proto.Acc.GetActiveEmails:input_type -> proto.Emails
	29, // 33: proto.Acc.SendCustomMail:input_type -> proto.SugMail
	7,  // 34: proto.Acc.ViaToken:output_type -> proto.AccPwd
	20, // 35: proto.Acc.ViaRole:output_type -> proto.Result
	0,  // 36: proto.Acc.AddRole:output_type -> proto.AEmpty
	7,  // 37: proto.Acc.AccRegister:output_type -> proto.AccPwd
	1,  // 38: proto.Acc.AccLogin:output_type -> proto.Token
	27, // 39: proto.Acc.RoleProfiles:output_type -> proto.RoleProfs
	27, // 40: proto.Acc.SearchInRole:output_type -> proto.RoleProfs
	0,  // 41: proto.Acc.UpdateEmail:output_type -> proto.AEmpty
	0,  // 42: proto.Acc.ResetSendPwd:output_type -> proto.AEmpty
	0,  // 43: proto.Acc.UnbindWechat:output_type -> proto.AEmpty
	1,  // 44: proto.Acc.GetToken:output_type -> proto.Token
	10, // 45: proto.Acc.GetAccEmails:output_type -> proto.IDEMails
	12, // 46: proto.Acc.GetProfile:output_type -> proto.Profile
	11, // 47: proto.Acc.GetContact:output_type -> proto.Contact
	15, // 48: proto.Acc.GetAvatars:output_type -> proto.Avatars
	15, // 49: proto.Acc.SearchAvatars:output_type -> proto.Avatars
	0,  // 50: proto.Acc.DeleteAcc:output_type -> proto.AEmpty
	2,  // 51: proto.Acc.StoreAddMach:output_type -> proto.UUID
	2,  // 52: proto.Acc.StoreAddComp:output_type -> proto.UUID
	0,  // 53: proto.Acc.StoreUpComp:output_type -> proto.AEmpty
	0,  // 54: proto.Acc.StoreBindWx:output_type -> proto.AEmpty
	0,  // 55: proto.Acc.StoreUnbindWx:output_type -> proto.AEmpty
	0,  // 56: proto.Acc.CompUnbindWx:output_type -> proto.AEmpty
	0,  // 57: proto.Acc.CompResetPwd:output_type -> proto.AEmpty
	0,  // 58: proto.Acc.StoreRename:output_type -> proto.AEmpty
	16, // 59: proto.Acc.StoreProfile:output_type -> proto.ProfStore
	17, // 60: proto.Acc.StoreProfiles:output_type -> proto.ProfStores
	6,  // 61: proto.Acc.GetActiveEmails:output_type -> proto.Emails
	0,  // 62: proto.Acc.SendCustomMail:output_type -> proto.AEmpty
	34, // [34:63] is the sub-list for method output_type
	5,  // [5:34] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_acc_proto_init() }
func file_proto_acc_proto_init() {
	if File_proto_acc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_acc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UIDS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccPwd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagPwd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDEMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDEMails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Avatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Avatars); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfStores); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxBind); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Machine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Composer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompSimp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleProf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleProfs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_acc_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SugMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_acc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_acc_proto_goTypes,
		DependencyIndexes: file_proto_acc_proto_depIdxs,
		MessageInfos:      file_proto_acc_proto_msgTypes,
	}.Build()
	File_proto_acc_proto = out.File
	file_proto_acc_proto_rawDesc = nil
	file_proto_acc_proto_goTypes = nil
	file_proto_acc_proto_depIdxs = nil
}
